-- Deploy sbgplants:plot_event_metadata_table_update to pg

BEGIN;

-- plot_event_id a primary key in this table
ALTER TABLE IF EXISTS sbgplants.plot_event_metadata
  DROP CONSTRAINT IF EXISTS  plot_event_metadata_pkey;

-- Add the new column with autogenerated UUID default value
ALTER TABLE sbgplants.plot_event_metadata
  ADD COLUMN plot_event_metadata_id UUID DEFAULT gen_random_uuid();

-- Set the new column as the primary key
ALTER TABLE sbgplants.plot_event_metadata
  ADD CONSTRAINT pk_plot_event_metadata_id PRIMARY KEY (plot_event_metadata_id);

-- add fk to fractional cover table
ALTER TABLE sbgplants.fractional_cover
  ADD COLUMN plot_event_metadata_id UUID;

-- create constraint
ALTER TABLE IF EXISTS sbgplants.fractional_cover
  ADD CONSTRAINT fractional_cover_plot_event_metadata_id_fkey FOREIGN KEY (plot_event_metadata_id)
  REFERENCES sbgplants.plot_event_metadata (plot_event_metadata_id)
  MATCH SIMPLE
  ON UPDATE NO ACTION
  ON DELETE NO ACTION
  NOT VALID;

COMMIT;
